= Spring Batch: Working With REST Resources
:source-highlighter: highlightjs
:source-language: java
Rashidi Zin <rashidi@zin.my>
2.0, September, 2023
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Implement batch operation for REST resources with https://spring.io/projects/spring-batch[Spring Batch]

== Background
Spring Batch allows us to perform large volumes of records from several resources such as https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/file/FlatFileItemReader.html[File],
https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/database/JpaPagingItemReader.html[Relational Database], and,
https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/json/JsonItemReader.html[JSON file] to name a few.

In this article, we will explore how to implement batch operation that reads from REST resources with Spring Batch through `JsonItemReader`. We will retrieve a list of users from https://jsonplaceholder.typicode.com/users[JSON Placeholder] and save them into a database.

== Job Configuration
Next is to implement the job that will be responsible to read from REST resource and save them into a database. `Job` consists of `Step` and `Step`
consists of `ItemReader` and `ItemWriter`. We will implement all of them in link:src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[UserJobConfiguration].

[source,java]
----
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=26..70]
----

From the code above, we can see that a `URL` form of `Resource` is assigned to `JsonItemReader`. We will depend on `JacksonJsonObjectRader` to convert response from link:https://jsonplaceholder.typicode.com/users[JSON Placeholder] to `User` object.

[source,java]
----
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=26..27]

include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=52..62]
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=69..70]
----

Now that we have implemented the `Job`, we can verify that it is working by executing an integration test.

== Verification
The following test will start the application which will automatically run the `Job` and save the result into a database. We will wait
up to 30 seconds before verifying the result.

[source,java]
----
include::src/test/java/zin/rashidi/boot/batch/user/UserBatchJobTests.java[lines=19..38]
----

To ensure that the implementation is working as expected, we will check the database, and it should contain 10 users, which is the total
number of users returned from the REST service.
