= Spring Batch: Working With REST Resources
:source-highlighter: highlight.js
:source-language: java
Rashidi Zin <rashidi@zin.my>
2.0, September 27, 2023
:toc:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials/tree/master/batch-rest-repository

Implement batch operation for REST resources with https://spring.io/projects/spring-batch[Spring Batch]

== Background
Spring Batch allows us to perform large volumes of records from several resources such as https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/file/FlatFileItemReader.html[File],
https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/database/JpaPagingItemReader.html[Relational Database], and,
https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/json/JsonItemReader.html[JSON file] to name a few.

In this article, we will explore how to implement batch operation that reads from REST resources with Spring Batch through `JsonItemReader`. We will retrieve a list of users from https://jsonplaceholder.typicode.com/users[JSON Placeholder] and save them into a database.

== Job Configuration
Next is to implement the job that will be responsible to read from REST resource and save them into a database. `Job` consists of `Step` and `Step`
consists of `ItemReader` and `ItemWriter`. We will implement all of them in link:{url-quickref}/src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[UserJobConfiguration].

[source,java]
----
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=26..70]
----

From the code above, we can see that a `URL` form of `Resource` is assigned to `JsonItemReader`. We will depend on `JacksonJsonObjectRader` to convert response from link:https://jsonplaceholder.typicode.com/users[JSON Placeholder] to `User` object.

[source,java]
----
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=26..27]

include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=52..62]
include::src/main/java/zin/rashidi/boot/batch/user/UserJobConfiguration.java[lines=69..70]
----

Now that we have implemented the `Job`, we can verify that it is working by executing an integration test.

== Verification
We will launch `userJob` which will retrieve list of `User` from https://jsonplaceholder.typicode.com/users[JSON Placeholder] and save them into a database.
Once completed then we will verify that the database contains the expected number of users.

[source,java]
----
include::src/test/java/zin/rashidi/boot/batch/user/UserBatchJobTests.java[lines=38..41]

include::src/test/java/zin/rashidi/boot/batch/user/UserBatchJobTests.java[lines=52..71]
include::src/test/java/zin/rashidi/boot/batch/user/UserBatchJobTests.java[lines=107..108]
----

Full implementation can be found in link:{url-quickref}/src/test/java/zin/rashidi/boot/batch/user/UserBatchJobTests.java[UserBatchJobTests].
