version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "antora"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
