site:
  title: Spring Boot Tutorials by Rashidi Zin
  url: https://rashidi.github.io/spring-boot-tutorials/
  start_page: root::README.adoc
content:
  sources:
    - url: https://example.com/docs-repo.git
      branches: [ main ]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
runtime:
  fetch: true