site:
  title: Spring Boot Tutorials
  url: https://rashidi.github.io/spring-boot-tutorials
  start_page: main::index.adoc
  keys:
    download_url: https://github.com/rashidi/spring-boot-tutorials/archive/refs/heads/master.zip

content:
  sources:
    - url: .
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

runtime:
  fetch: true
