= Spring Boot: Samples &amp; Tutorials
:nofooter:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials

Samples and tutorials for https://spring.io/projects/spring-boot[Spring Boot] modules such as, but not limited to,
Spring Data, Spring Batch, Spring Cloud, Spring Security, Spring GraphQL, and Spring Test. Each tutorial is equipped
with source code in individual submodules and can be found on {url-quickref}[GitHub].

image:https://img.shields.io/badge/Java_-21-blue?style=flat-square[Static Badge]
image:https://img.shields.io/gradle-plugin-portal/v/org.springframework.boot?style=flat-square&logo=springboot&label=Spring%20Boot[Gradle Plugin Portal Version]
image:https://img.shields.io/github/license/rashidi/spring-boot-tutorials?style=flat-square&color=blue[GitHub License]
image:https://img.shields.io/github/actions/workflow/status/rashidi/spring-boot-tutorials/build-and-publish.yml?style=flat-square&logo=githubactions&color=blue[GitHub Actions Workflow Status]
image:https://img.shields.io/sonar/coverage/rashidi_spring-boot-tutorials?server=https%3A%2F%2Fsonarcloud.io&style=flat-square&color=blue[Sonar Coverage]
image:https://img.shields.io/github/stars/rashidi/spring-boot-tutorials?style=flat-square&logo=github[GitHub Repo stars, link={url-quickref}]

== Motivation

While it is common to find https://spring.io/projects/spring-boot[Spring Boot] tutorials on the Internet, it is
challenging to find tutorials that are up-to-date and include automated tests to demonstrate the implementation and
ensure stability.

== Commitment

Continual improvement is fundamental in software development. This repository is committed in ensuring adherence to
best practices and keeping all dependencies up-to-date. The quality of these tutorials and the knowledge imparted is,
and always will be, my primary goal.

With the help of https://github.com/dependabot[Dependabot], each tutorial is also kept up-to-date with the latest
dependencies. Currently, we are using Java https://adoptium.net/en-GB/temurin/releases/?version=21[Temurin 21]
with https://plugins.gradle.org/plugin/org.springframework.boot/3.4.3[Spring Boot 3.4.3].

== Topics

|===
|Topic |Description

|link:batch-rest-repository[Spring Batch: Batch Job With REST API source] |Spring Batch job that reads information from REST API
|link:batch-skip-step[Spring Batch: Skip Specific Data] |Skip processing specific data based on business logic in Spring Batch
|link:cloud-jdbc-env-repo[Spring Cloud Environment Repository] |Store environment properties in MySQL database with Spring Cloud Environment Repository
|link:data-domain-events[Spring Data Domain Events] |Publish Domain Events with Spring Data
|link:data-envers-audit[Spring Data Envers Audit] |Enable with Entity Revisions using Spring Data Envers
|link:data-jdbc-audit[Spring Data JDBC Audit] |Enable Audit with Spring Data JDBC
|link:data-jpa-audit[Spring Data JPA Audit] |Enable Audit with Spring Data JPA
|link:data-jpa-event[Spring Data JPA: Event Driven] |Implement `Entity` validation at `Repository` level through `EventListeners`
|link:data-jpa-filtered-query[Spring Data JPA: Global Filtered Query] |Implement global filtered query with Spring Data JPA by defining `repositoryBaseClass`
|link:data-mongodb-audit[Spring Data MongoDB Audit] |Enable Audit with Spring Data MongoDB
|link:data-mongodb-full-text-search[Spring Data MongoDB: Full Text Search] |Implement link:https://docs.mongodb.com/manual/text-search/[MongoDB Full Text Search] with Spring Data MongoDB
|link:data-mongodb-transactional[Spring Data MongoDB: Transactional] |Enable `@Transactional` support for Spring Data MongoDB
|link:data-repository-definition[Spring Data: Repository Definition] |Implement custom repository interfaces with `@RepositoryDefinition` annotation
|link:data-rest-validation[Spring Data REST: Validation] |Perform validation with Spring Data REST
|link:graphql[Spring GraphQL Server] |Implement GraphQL server with Spring GraphQL Server
|link:jooq[jOOQ] | Implement an alternative to Jpa using https://www.jooq.org/[jOOQ] and Gradle
|link:data-mongodb-tc-data-load[Spring Test: Load data with Testcontainers] |Load test data with Testcontainers instead of `BeforeEach`
|link:test-execution-listeners[Spring Test: Test Execution Listeners] |Implement custom `TestExecutionListener` to manage data in tests
|link:test-rest-assured[Spring Test: Integration with RestAssured] | Implement Behaviour Driven Development with https://rest-assured.io/[RestAssured]
|link:test-slice-tests-rest[Spring Test: Implementing Slice Tests for REST application] | Dive into available options to implement tests with Spring Boot's test components
|link:web-rest-client[Spring Web: REST Clients for calling Synchronous API] | Implement REST client to perform synchronous API calls
|===
