spring.application.name=ai-redis
spring.ai.vectorstore.redis.index-name=spring-ai-document-index
spring.ai.vectorstore.redis.prefix=spring-ai-document:
spring.data.redis.client-type=jedis
spring.ai.vectorstore.redis.initialize-schema=true
