= Spring Data: Domain Events Example
Rashidi Zin <rashidi@zin.my>
1.0, July 30, 2023: Initial version
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Reduce method complexity by utilising `@DomainEvents` from link:https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.domain-events[Spring Data JPA].

== Background
In this repository we will explore Spring Data JPA helps us to adhere to [Single Responsibility](https://en.wikipedia.org/wiki/Single-responsibility_principle), a component of [SOLID Principles](https://en.wikipedia.org/wiki/SOLID).

We will reduce responsibilities of a method that does more than one thing.

== Scenario
This repository demonstrates a scenario where once a book is purchased, its total availability will be reduced.

== Implementation

=== Integration End-to-end Test
In the spirit of TDD, we will start by implementing an integration end-to-end test.

[source,java]
----
class BookPurchaseTests {

    @Autowired
    private TestRestTemplate client;

    @Test
    @DisplayName("Given total book availability is 100 When a book is purchased Then total book availability should be 99")
    void purchase() {
        client.delete("/books/{id}/purchase", book.getId());

        var availability = availabilities.findByIsbn(book.getIsbn());

        assertThat(availability).get()
                .extracting("total")
                .isEqualTo(99);
    }

}
----

Full implementation can be found in link:src/test/java/zin/rashidi/boot/data/de/availability/BookPurchaseTests.java[BookPurchaseTests.java].
This test will be unaffected by refactoring we will be doing through out the process.

=== Domain and Repository class

Our domain class, link:src/main/java/zin/rashidi/boot/data/de/book/Book.java[Book.java], will hold information about the event that will be published.

[source,java]
----
@Entity
public class Book extends AbstractAggregateRoot<Book> {

    @Id
    @GeneratedValue
    private Long id;
    private String title;
    private String author;
    private Long isbn;

    // omitted for brevity

    public Book purchase() {
        registerEvent(new BookPurchaseEvent(this));
        return this;
    }

}
----

The class will publish link:src/main/java/zin/rashidi/boot/data/de/book/BookPurchaseEvent.java[BookPurchaseEvent.java] when a book is purchased.

Next is to implement a repository classes for `Book` and link:src/main/java/zin/rashidi/boot/data/de/availability/BookAvailability.java[BookAvailability.java].

[source,java]
----
public interface BookRepository extends JpaRepository<Book, Long> {}
----

[source,java]
----
interface BookAvailabilityRepository extends JpaRepository<BookAvailability, Long> {

    Optional<BookAvailability> findByIsbn(Long isbn);

}
----

==== REST Resource Class

link:src/main/java/zin/rashidi/boot/data/de/book/BookResource.java[BookResource] is a typical `@RestController` class which will trigger `Book.purchase`.

[source,java]
----
@RestController
class BookResource {

    private final BookRepository repository;

    BookResource(BookRepository repository) {
        this.repository = repository;
    }

    @Transactional
    @DeleteMapping("/books/{id}/purchase")
    public void purchase(@PathVariable Long id) {
        repository.findById(id).map(Book::purchase).ifPresent(repository::delete);
    }

}
----

==== Event Listener Class

Finally, we will implement a `@Service` class that will observe link:src/main/java/zin/rashidi/boot/data/de/book/BookPurchaseEvent.java[BookPurchaseEvent] and reduce the total availability of the book.

[source,java]
----
@Service
class BookAvailabilityManagement {

    @TransactionalEventListener
    @Transactional(propagation = REQUIRES_NEW)
    public void updateTotal(BookPurchaseEvent event) {
        var book = event.getSource();

        repository.findByIsbn(book.getIsbn()).map(BookAvailability::reduceTotal).ifPresent(repository::save);
    }

}
----

== Verification

By executing `BookPurchaseTests.purchase`, we will see that the test passes.