= Spring Data MongoDb with Testcontainers
:source-highlighter: highlight.js
Rashidi Zin <rashidi@zin.my>
3.0, November 24, 2024: Replace usage of mongo-init.js with Spring's RepositoryPopulator
:nofooter:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials/tree/master/data-mongodb-tc-data-load

Preloaded data for testing.


== Background
It is common to have preloaded data when we are testing our delete, read, and update operations. One of the most common approaches is to
load them programmatically. In this example, we will see how we can use Testcontainers to load data into our MongoDB instance.

== Load Data Programmatically
It is common that we load data programmatically. There are several approaches to do this.

=== Using `@BeforeEach` and `@AfterEach`
`@BeforeEach` will be executed before each test method execution while `@AfterEach` will be executed after test method executed. In this example,
we will use `@BeforeEach` to load data and `@AfterEach` to delete data.

[source,java]
----
@DataMongoTest
@Testcontainers
class UserRepositoryTests {

    @Container
    @ServiceConnection
    private static final MongoDBContainer mongo = new MongoDBContainer("mongo:latest");

    @Autowired
    private UserRepository repository;

    @BeforeEach
    void create() {
        repository.save(new User(null, "rashidi.zin", "Rashidi Zin"));
    }

    @AfterEach
    void delete() {
        repository.deleteAll();
    }

    @Test
    @DisplayName("Given there is a user with username rashidi.zin and name Rashidi Zin When I search for username rashidi.zin Then user with provided username should be returned")
    void findByUsername() {
        var user = repository.findByUsername("rashidi.zin");

        assertThat(user)
                .extracting("name")
                .isEqualTo("Rashidi Zin");
    }

    @Test
    @DisplayName("Given there is no user with username zaid.zin When I search for username zaid.zin Then null should be returned")
    void findByUsernameWithNonExistingUsername() {
        var user = repository.findByUsername("zaid.zin");

        assertThat(user).isNull();
    }
}
----

While this approach works, it might be time-consuming when we have many methods to be executed. Another approach is to use `@TestExecutionListeners`

=== Using `@TestExecutionListeners`
`@TestExecutionListeners` allows us to register implemented https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/TestExecutionListener.html[`TestExecutionListener`]
which can be used to execute code before and after test execution.

The following `TestExecutionListener` is used to load data before executing the test class and remove all data after test class has been executed.

[source,java]
----
class UserTestExecutionListener extends AbstractTestExecutionListener {

    private User user;


    @Override
    public void beforeTestClass(TestContext testContext) {
        var mongo = testContext.getApplicationContext().getBean(MongoOperations.class);

        user = mongo.insert(new User(null, "rashidi.zin", "Rashidi Zin"));
    }

    @Override
    public void afterTestClass(TestContext testContext) {
        var mongo = testContext.getApplicationContext().getBean(MongoOperations.class);

        mongo.remove(user);
    }

}
----

Then we will include it in our test class:

[source,java]
----
@DataMongoTest
@Import(UserRepositoryTests.TestcontainersConfiguration.class)
@TestExecutionListeners(listeners = UserTestExecutionListener.class, mergeMode = MERGE_WITH_DEFAULTS)
class UserRepositoryTests {

    @Autowired
    private UserRepository repository;

    @Test
    @DisplayName("Given there is a user with username rashidi.zin and name Rashidi Zin When I search for username rashidi.zin Then user with provided username should be returned")
    void findByUsername() {
        var user = repository.findByUsername("rashidi.zin");

        assertThat(user)
                .extracting("name")
                .isEqualTo("Rashidi Zin");
    }

    @Test
    @DisplayName("Given there is no user with username zaid.zin When I search for username zaid.zin Then null should be returned")
    void findByUsernameWithNonExistingUsername() {
        var user = repository.findByUsername("zaid.zin");

        assertThat(user).isNull();
    }

    @TestConfiguration(proxyBeanMethods = false)
    @ImportAutoConfiguration(TestcontainersPropertySourceAutoConfiguration.class)
    static class TestcontainersConfiguration {

        @Bean
        MongoDBContainer mongoDbContainer(DynamicPropertyRegistry registry) {
            var mongo = new MongoDBContainer("mongo:latest");

            registry.add("spring.data.mongodb.uri", mongo::getReplicaSetUrl);

            return mongo;
        }

    }
}
----

In this example, we are using `@TestExecutionListeners` to register `UserTestExecutionListener` which will be executed before and after test class execution. Alternatively, we also no longer utilise on
helpful annotations - `@Testcontainers`, `@Container`, and `@ServiceConnection`.

== Load Data Using RepositoryPopulators
Next approach is to load data using https://docs.spring.io/spring-data/mongodb/reference/repositories/core-extensions.html#core.repository-populators[RepositoryPopulators] and Testcontainers.
We will start by creating link:{url-quickref}/src/test/resources/users.json[users.json] and populate it with the following content.

[source,json]
----
[{
  "_class": "zin.rashidi.data.mongodb.tc.dataload.user.User",
  "name": "Rashidi Zin",
  "username": "rashidi.zin"
}]
----

First, we will have to add `jackson-databind` as our dependency in link:${url-quickref}/build.gradle[build.gradle].

[source,groovy]
----
dependencies {
    testImplementation "com.fasterxml.jackson.core:jackson-databind"
}
----

Next we will create a `@TestConfiguration` class which will define `RepositoryPopulator`.

[source,java]
----
class UserRepositoryTests {

    @TestConfiguration
    static class RepositoryPopulatorTestConfiguration {

        @Bean
        public Jackson2RepositoryPopulatorFactoryBean jacksonRepositoryPopulator() {
            var populator = new Jackson2RepositoryPopulatorFactoryBean();
            populator.setResources(new Resource[] { new ClassPathResource("users.json") });
            return populator;
        }
    }

}
----

Then we will inform link:${url-quickref}/src/test/java/zin/rashidi/data/mongodb/tc/dataload/user/UserRepositoryTests.java[UserRepositoryTests] to include `RepositoryPopulatorTestConfiguration`.

[source,java]
----
@DataMongoTest(includeFilters = @Filter(type = ASSIGNABLE_TYPE, classes = UserRepositoryTests.RepositoryPopulatorTestConfiguration.class))
class UserRepositoryTests {

    @TestConfiguration
    static class RepositoryPopulatorTestConfiguration {

        @Bean
        public Jackson2RepositoryPopulatorFactoryBean jacksonRepositoryPopulator() {
            var populator = new Jackson2RepositoryPopulatorFactoryBean();
            populator.setResources(new Resource[] { new ClassPathResource("users.json") });
            return populator;
        }
    }

}
----

Finally, the usual setup to include `@TestContainers` and `MongoDBContainer`.

[source,java]
----
@Testcontainers
@DataMongoTest(includeFilters = @Filter(type = ASSIGNABLE_TYPE, classes = UserRepositoryTests.RepositoryPopulatorTestConfiguration.class))
class UserRepositoryTests {

    @Container
    @ServiceConnection
    private static final MongoDBContainer mongo = new MongoDBContainer("mongo:latest");

    @TestConfiguration
    static class RepositoryPopulatorTestConfiguration {

        @Bean
        public Jackson2RepositoryPopulatorFactoryBean jacksonRepositoryPopulator() {
            var populator = new Jackson2RepositoryPopulatorFactoryBean();
            populator.setResources(new Resource[] { new ClassPathResource("users.json") });
            return populator;
        }
    }

}
----

Once everything is ready, we will add our tests.

[source,java]
----
@Testcontainers
@DataMongoTest(includeFilters = @Filter(type = ASSIGNABLE_TYPE, classes = UserRepositoryTests.RepositoryPopulatorTestConfiguration.class))
class UserRepositoryTests {

    @Container
    @ServiceConnection
    private static final MongoDBContainer mongo = new MongoDBContainer("mongo:latest");

    @Autowired
    private UserRepository repository;

    @Test
    @DisplayName("Given there is a user with username rashidi.zin and name Rashidi Zin When I search for username rashidi.zin Then user with provided username should be returned")
    void findByUsername() {
        var user = repository.findByUsername("rashidi.zin");

        assertThat(user)
                .extracting("name")
                .isEqualTo("Rashidi Zin");
    }

    @Test
    @DisplayName("Given there is no user with username zaid.zin When I search for username zaid.zin Then null should be returned")
    void findByUsernameWithNonExistingUsername() {
        var user = repository.findByUsername("zaid.zin");

        assertThat(user).isNull();
    }

    @TestConfiguration
    static class RepositoryPopulatorTestConfiguration {

        @Bean
        public Jackson2RepositoryPopulatorFactoryBean jacksonRepositoryPopulator() {
            var populator = new Jackson2RepositoryPopulatorFactoryBean();
            populator.setResources(new Resource[] { new ClassPathResource("users.json") });
            return populator;
        }
    }

}
----

With that, data will be loaded into MongoDB before the test execution. Full implementation of link:{url-quickref}/src/test/java/zin/rashidi/data/mongodb/tc/dataload/user/UserRepositoryTests.java[`UserRepositoryTests`]:

This also allows us to have a single source of truth in managing data for our tests.
