= Spring Boot: Samples & Tutorials
:nofooter:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials

Samples and tutorials for https://spring.io/projects/spring-boot[Spring Boot] modules such as, but not limited to,
Spring Data, Spring Batch, Spring Cloud, Spring Security, Spring GraphQL, and Spring Test. Each tutorial is equipped
with source code in individual submodules and can be found on {url-quickref}[GitHub].

== Motivation

While it is common to find https://spring.io/projects/spring-boot[Spring Boot] tutorials on the Internet, it is
challenging to find tutorials that are up-to-date and include automated tests to demonstrate the implementation and
ensure stability.

== Commitment

Continual improvement is fundamental in software development. This repository is committed in ensuring adherence to
best practices and keeping all dependencies up-to-date. The quality of these tutorials and the knowledge imparted is,
and always will be, my primary goal.

With the help of https://github.com/dependabot[Dependabot], each tutorial is also kept up-to-date with the latest
dependencies. Currently, we are using Java https://adoptium.net/en-GB/temurin/releases/?version=21[Temurin 21]
with https://plugins.gradle.org/plugin/org.springframework.boot/3.4.4[Spring Boot 3.4.4]..