= GraphQL With Spring Boot
:source-highlighter: highlight.js
Rashidi Zin <rashidi@zin.my>
1.0, September 3, 2023
:toc:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials/tree/master/graphql

Implementing https://graphql.org/[GraphQL] server with https://spring.io/guides/gs/graphql-server/[Spring Boot GraphQL Server].

== Background

GraphQL provides the flexibility for clients to retrieve fields that are only relevant to them. In this tutorial we will
explore how we can implement GraphQL server with Spring Boot.

== Server Implementation

=== schema.graphqls

[source,graphql]
----
include::src/main/resources/graphql/schema.graphqls[lines=1..29]
----

This is the schema that inform our clients on available fields and queries. Next is to implement a `@Controller` that
handle all requests.

=== Controller

[source, java]
----
include::src/main/java/zin/rashidi/boot/graphql/book/BookResource.java[lines=12..31]
----

link:{url-quickref}/src/main/java/zin/rashidi/boot/graphql/book/BookResource.java[BookResource] implements two types of services -
`findAll`, a service without parameter and `findByTitle`, a service with a parameter. Both services are annotated with
`@QueryMapping` to indicate that they are GraphQL queries.

== Verification

We will utilise `@GraphQlTest` to verify our implementation.

=== Integration Test

[source, java]
----
include::src/test/java/zin/rashidi/boot/graphql/book/BookResourceTests.java[lines=18..77]
----

=== Client schema definition

In order to map the response to a Java object, we need to define the schema of the response. This is done in link:{url-quickref}/src/test/resources/graphql-test/books.graphql[books.graphl].

[source, graphql]
----
include::src/test/resources/graphql-test/books.graphql[]
----

By executing tests implemented in link:{url-quickref}/src/test/java/zin/rashidi/boot/graphql/book/BookResourceTests.java[BookResourceTests], we can verify that our implementation is working as expected.
