= Testcontainers setup with Replica Set
:source-highlighter: highlight.js

The simplest and most secure way to connect Testcontainers `MongoDBContainer` is by using `@ServiceConnection`. However, Spring Boot tests currently do not automatically handle MongoDB's *Replica Set*. Given `@Transactional` requires a *Replica Set*, the application will encounter an error during startup.

[source,text]
----
MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected
----

We must manually define `.withReplicaSet()` to run tests that interact with transactional operations. Let's see how it is done in action.

== Initial Setup

We will create a `User` document that is managed by `UserRepository` and exposed via `UserController` to process creation request. When the user is created, the system must set the `status` to `ACTIVE`.

[source,java]
----
@RestController
class UserController {

    private final UserRepository repository;

    UserController(UserRepository repository) {
        this.repository = repository;
    }

    @PostMapping("/users")
    @Transactional
    public User create(@RequestBody User user) {
        user.setStatus(ACTIVE);

        return repository.save(user);
    }

}
----

== Integration Testing with Testcontainers

Now we can proceed to prepare the test. We will use `RestTestClient` to perform a `POST` request and verify if `status` is set to `ACTIVE`. Notice `MongoDBContainer` is defined with `.withReplicaSet()`? That will ensure the container is started with a _Replica Set_.

[source,java]
----
@AutoConfigureRestTestClient
@SpringBootTest(webEnvironment = RANDOM_PORT)
@Testcontainers
class CreateUserTests {

    @Container
    @ServiceConnection
    private static final MongoDBContainer mongo = new MongoDBContainer("mongo:latest").withReplicaSet();

    @Autowired
    private RestTestClient restTemplate;

    @Test
    void create() {

        var body = """
                {
                  "username": "rashidi.zin",
                  "name": "Rashidi Zin"
                }
                """;

        var response = restTemplate.post().uri("/users")
                .contentType(MediaType.APPLICATION_JSON)
                .body(body)
                .exchange()
                .expectStatus().isOk()
                .returnResult(User.class);

        var createdUser = response.getResponseBody();

        assertThat(createdUser).extracting("status").isEqualTo(ACTIVE);
    }

}
----
