spring.application.name=batch-jdbc-update

# Batch requires schema initialization in tests if using testcontainers, or we can use spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.initialize-schema=always
