= Spring Data Jpa: Global Filter Query
:source-highlighter: highlight.js
Rashidi Zin <rashidi@zin.my>
1.0, October 12, 2023
:toc:
:nofooter:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials/tree/master/data-jpa-filtered-query

Implement global filter query which involves several `Entity` with Spring Data Jpa.

== Background

It is common that we need to implement similar filter query in our application. For example, we have `User` and `Post` entities whereby both
contains `status` field. We would want to ensure that when these `Entity` is retrieved, only `ACTIVE` ones will be returned.

In this tutorial we will implement a global filter by utilising Spring Data Jpa `repositoryBaseClass`.

== Integration Tests

There are two tests which involves two entities - `User` and `Country`. `User` contains a `status` field while `Country` does not.

When `findAll` is triggered for `User` then only `ACTIVE` users will be returned.

[source,java]
----
include::src/test/java/zin/rashidi/boot/data/jpa/user/UserRepositoryTests.java[lines=33..34]
include::src/test/java/zin/rashidi/boot/data/jpa/user/UserRepositoryTests.java[lines=39..58]
----

However, when `findAll` is triggered for `Country` then all countries will be returned.

[source,java]
----
include::src/test/java/zin/rashidi/boot/data/jpa/country/CountryRepositoryTests.java[lines=31..32]
include::src/test/java/zin/rashidi/boot/data/jpa/country/CountryRepositoryTests.java[lines=37..57]
----

== Configuration Class

We will start by defining `repositoryBaseClass`

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/jpa/jpa/JpaCustomBaseRepository.java[lines=18..31]
----

In `JpaCustomBaseRepository` we will define a method `findAll` which will be used by all `Entity` to retrieve data. This method will filter
any `Entity` with `status` field and return only `ACTIVE` ones.

To recap, link:{url-quickref}/src/main/java/zin/rashidi/boot/data/jpa/user/User.java[`User`] contains `status`  field while
link:{url-quickref}/src/main/java/zin/rashidi/boot/data/jpa/country/Country.java[`Country`] does not. Therefore, when `findAll` is triggered for `User` then
only `ACTIVE` users will be returned. However, when `findAll` is triggered for `Country` then all countries will be returned.

Next we will inform Spring Data Jpa to use `JpaCustomBaseRepository` as the base class for all `Entity` by defining `@EnableJpaRepositories`
in link:{url-quickref}/src/main/java/zin/rashidi/boot/data/jpa/jpa/JpaConfiguration.java[`JpaConfiguration`].

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/jpa/jpa/JpaConfiguration.java[lines=9..16]
----

== Verification

To ensure that our implementation is working as expected, we will execute tests defined in link:{url-quickref}/src/test/java/zin/rashidi/boot/data/jpa/user/UserRepositoryTests.java[`UserRepositoryTests`] and link:{url-quickref}/src/test/java/zin/rashidi/boot/data/jpa/country/CountryRepositoryTests.java[`CountryRepositoryTests`].

Both tests should pass.
