= Spring Data MongoDB: Full Text Search
:source-highlighter: highlightjs
:source-language: java
Rashidi Zin <rashidi@zin.my>
1.0, September 25, 2023
:toc:
:icons: font
:url-quickref: https://github.com/rashidi/spring-boot-tutorials/tree/master/data-mongodb-full-text-search

Implement link:https://docs.mongodb.com/manual/text-search/[MongoDB Full Text Search] with link:https://spring.io/projects/spring-data-mongodb[Spring Data MongoDB].

== Background

MongoDB full text search provides the flexibility to perform search entries through multiple fields. In this example we will explore how to implement full text search with Spring Data MongoDB.

== Verification
Given we have the following entries in link:{url-quickref}/src/main/java/zin/rashidi/boot/data/mongodb/character/Character.java[Character]:

.Characters
|===
|Name |Publisher

|Captain Marvel
|Marvel

|Joker
|DC

|Thanos
|Marvel
|===

When searching for `captain marvel` then the following results should be returned

.Characters that contains the keyword `captain` or `marvel`
|===
|Name |Publisher

|Captain Marvel
|Marvel

|Thanos
|Marvel
|===

This is demonstrated in link:{url-quickref}/src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[CharacterRepositoryTests].

== Implementation
We will start by defining the `Character` entity.

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/mongodb/character/Character.java[lines=11..28]
----

=== With Predefined Index
If respective fields are already `indexed` then we can utilise Spring Data query generation to perform full text search.

This can be done by creating a method that takes `TextCriteria` as parameter:

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/mongodb/character/CharacterRepository.java[lines=13..17]
----

This method can then be used in the following manner:

[source,java]
----
include::src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[lines=25..52]
include::src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[lines=79..80]
----

=== Without Predefined Index
Without predefined index, we will need to implement a custom repository implementation. We will start by defining a custom repository interface, link:{url-quickref}/src/main/java/zin/rashidi/boot/data/mongodb/character/CharacterSearchRepository.java[CharacterSearchRepository]:

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/mongodb/character/CharacterSearchRepository.java[lines=10..14]
----

Next, implement the custom repository interface in link:{url-quickref}/src/main/java/zin/rashidi/boot/data/mongodb/character/CharacterSearchRepositoryImpl.java[CharacterSearchRepositoryImpl]:

[source,java]
----
include::src/main/java/zin/rashidi/boot/data/mongodb/character/CharacterSearchRepositoryImpl.java[lines=14..33]
----

This implementation will `indexed` searchable fields, i.e. `name` and `publisher` before searching the `Document`.

Finally, we will verify our custom implementation through integration test:

[source,java]
----
include::src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[lines=27..37]

include::src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[lines=56..64]
include::src/test/java/zin/rashidi/boot/data/mongodb/character/CharacterRepositoryTests.java[lines=79..80]
