CREATE TABLE author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE book
(
    isbn      VARCHAR(14) PRIMARY KEY,
    title     TEXT NOT NULL,
    author_id BIGINT       NOT NULL,
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
            REFERENCES author (id)
);

INSERT INTO author (name) VALUES ('Sun Tzu');