name: Build and Publish Antora Site

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'antora-playbook.yml'
      - '.github/workflows/build-and-publish-antora.yml'
      - '**/README.adoc'
      - '**/**.hbs'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Antora
        run: npm i -g @antora/cli@3.1 @antora/site-generator@3.1

      - name: Generate site
        run: antora --fetch antora-playbook.yml

      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v5
        with:
          name: site
          path: build/site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4