# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  batch-rest-repository:
    name: Build batch-rest-repository
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: batch-rest-repository
  batch-skip-step:
    name: Build batch-skip-step
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: batch-skip-step

  cloud-jdbc-env-repo:
    name: Build cloud-jdbc-env-repo
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: cloud-jdbc-env-repo

  data-domain-events:
    name: Build data-domain-events
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-domain-events
  data-envers-audit:
    name: Build data-envers-audit
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-envers-audit
  data-jpa-audit:
    name: Build data-jpa-audit
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-jpa-audit
  data-jpa-event:
    name: Build data-jpa-event
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-jpa-event
  data-jpa-filtered-query:
    name: Build data-jpa-filtered-query
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-jpa-filtered-query
  data-mongodb-audit:
    name: Build data-mongodb-audit
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-mongodb-audit
  data-mongodb-full-text-search:
    name: Build data-mongodb-full-text-search
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-mongodb-full-text-search
  data-mongodb-tc-data-load:
    name: Build data-mongodb-tc-data-load
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-mongodb-tc-data-load
  data-mongodb-transactional:
    name: Build data-mongodb-transactional
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-mongodb-transactional
  data-rest-validation:
    name: Build data-rest-validation
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: data-rest-validation

  graphql:
    name: Build graphql
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: graphql
  jooq:
    name: Build jooq
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: jooq
  langchain4j:
    name: Build langchain4j
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: langchain4j

  test-execution-listeners:
    name: Build test-execution-listeners
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: test-execution-listeners
  test-rest-assured:
    name: Build test-rest-assured
    uses: ./.github/workflows/gradle-reusable-build.yml
    with:
      submodule: test-rest-assured