name: Gradle Reusable Build

on:
  workflow_call:
    inputs:
      submodule:
        required: true
        type: string

jobs:
  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: always
      - name: Build Submodule
        id: gradle-build-submodule
        run: ./gradlew ${{ inputs.submodule }}:build