@startuml
set separator none
title Student

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ModulithApplication.ModulithApplication_boundary", "ModulithApplication", $tags="") {
  Component(ModulithApplication.ModulithApplication.Student, "Student", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml